version: '3'
services:
  web:
    container_name: phpdevbox_web
    image: hectorrojas/phpdevbox:7.3-fpm
    volumes:
      - "~/.composer:/home/phpdevbox/.composer"
      - "~/.ssh:/home/phpdevbox/.ssh"
      - ./apache/log/apache2:/var/log/apache2:cached
      - ./webroot:/var/www/phpdevbox:consistent
    expose:
      - "9000"
    ports:
      - "80:80"
      - "443:443"
      - "4022:22"
  db:
    container_name: phpdevbox_db
    image: mariadb:10.2
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=phpdevbox
      - MYSQL_DATABASE=phpdevbox
      - MYSQL_USER=phpdevbox
      - MYSQL_PASSWORD=phpdevbox
    ports:
      - "3306:3306"
  elasticsearch:
    image: hectorrojas/elasticsearch:6.5

