version: '2'
services:
  web:
    image: hectorrojas/phpdevbox:7.3-fpm
    volumes:
      - "~/.composer:/home/phpdevbox/.composer"
      - "~/.ssh:/home/phpdevbox/.ssh"
      - ./var/log/apache2:/var/log/apache2:cached
      - ./var/spool/mail:/var/spool/mail/:cached
      - ./webroot:/var/www/phpdevbox:consistent
    expose:
      - "9000"
    ports:
      - "80:80"
      - "443:443"
      - "4022:22"
    depends_on:
      - db
    extends: generic
  generic:
    image: alpine
    environment:
      - PHP_MEMORY_LIMIT=4096M
      - UPLOAD_MAX_FILESIZE=64M
      - APP_ROOT=/app
      - XDEBUG_CONFIG=remote_host=host.docker.internal
  db:
    image: mariadb:10.2
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=phpdevbox
      - MYSQL_DATABASE=phpdevbox
      - MYSQL_USER=phpdevbox
      - MYSQL_PASSWORD=phpdevbox
    ports:
      - "3306:3306"
  elasticsearch:
    image: hectorrojas/elasticsearch:6.5

