version: '2'
services:
  web:
    image: hectorrojas/phpdevbox:7.3-fpm
    volumes:
      - ./var/log/apache2:/var/log/apache2:cached
      - ./webroot:/app:consistent
    environment:
      - APP_ROOT=/app
      - PHP_MEMORY_LIMIT=4G
      - MAX_EXECUTION_TIME=18000
      - UPLOAD_MAX_FILESIZE=64M
      - POST_MAX_SIZE=64M
      - GC_MAXLIFETIME=7200
      - LOG_ERRORS=1
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl sodium xdebug'
    expose:
      - "9000"
    ports:
      - "80:80"
      - "443:443"
      - "4022:22"
    depends_on:
      - db
  db:
    image: mariadb:10.2
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=application
      - MYSQL_USER=phpdevbox
      - MYSQL_PASSWORD=phpdevbox
    ports:
      - "3306:3306"
  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  elasticsearch:
    image: hectorrojas/elasticsearch:6.5
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ports:
          - "9200:9200"
          - "9300:9300"
