version: '3'
services:
    web:
        container_name: phpdevbox_web
        image: hectorrojas/phpdevbox:zend-7.1-fpm
        volumes:
          - "~/.composer:/home/phpdevbox/.composer"
          - "~/.ssh:/home/phpdevbox/.ssh"
          - "./shared/log/apache2:/var/log/apache2"
          - ./shared/webroot:/var/www/phpdevbox:consistent
        expose:
          - "9000"
        ports:
          - "80:80"
          - "443:443"
          - "4022:22"

    db:
        container_name: phpdevbox_db
        image: mysql:5.7
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=mysql
        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/log/mysql:/var/log/mysql"
