version: '2'
services:
  web:
    image: hectorrojas/phpdevbox:7.3-fpm
    volumes:
      - "~/.composer:/home/phpdevbox/.composer"
      - "~/.ssh:/home/phpdevbox/.ssh"
      - ./var/log/apache2:/var/log/apache2:cached
      - ./var/spool/mail:/var/spool/mail/:cached
      - ./webroot:/app:consistent
    expose:
      - "9000"
    ports:
      - "80:80"
      - "443:443"
      - "4022:22"
    depends_on:
      - db
    extends: generic
  generic:
    image: alpine
    environment:
      - PHP_MEMORY_LIMIT=4G
      - UPLOAD_MAX_FILESIZE=64M
      - APP_ROOT=/app
      - PHP_IDE_CONFIG=serverName=phpdevbox
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl sodium xdebug'
  db:
    image: mariadb:10.2
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=phpdevbox
      - MYSQL_DATABASE=phpdevbox
      - MYSQL_USER=phpdevbox
      - MYSQL_PASSWORD=phpdevbox
    ports:
      - "3306:3306"
  elasticsearch:
    image: hectorrojas/elasticsearch:6.5
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ports:
          - "9200:9200"
          - "9300:9300"

